// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6W-RXN1qOfvBzFZ6Y3ilGCmSHm-g_UGE',
    appId: '1:101671064485:web:ed19d09d6a5e58f353ce4c',
    messagingSenderId: '101671064485',
    projectId: 'desire-b0903',
    authDomain: 'desire-b0903.firebaseapp.com',
    storageBucket: 'desire-b0903.firebasestorage.app',
    measurementId: 'G-E8FCZ7WB6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOPxHZnzcOQzKQuIOBJthK7x0KepIuHbg',
    appId: '1:101671064485:android:eb87ea82ad14e41953ce4c',
    messagingSenderId: '101671064485',
    projectId: 'desire-b0903',
    storageBucket: 'desire-b0903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR6atUTniNZk9RbD2RC7Il2G7DiPGvuqg',
    appId: '1:101671064485:ios:98c160873b612b1653ce4c',
    messagingSenderId: '101671064485',
    projectId: 'desire-b0903',
    storageBucket: 'desire-b0903.firebasestorage.app',
    iosBundleId: 'com.desire.desire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR6atUTniNZk9RbD2RC7Il2G7DiPGvuqg',
    appId: '1:101671064485:ios:98c160873b612b1653ce4c',
    messagingSenderId: '101671064485',
    projectId: 'desire-b0903',
    storageBucket: 'desire-b0903.firebasestorage.app',
    iosBundleId: 'com.desire.desire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6W-RXN1qOfvBzFZ6Y3ilGCmSHm-g_UGE',
    appId: '1:101671064485:web:93cbe084de7fd19453ce4c',
    messagingSenderId: '101671064485',
    projectId: 'desire-b0903',
    authDomain: 'desire-b0903.firebaseapp.com',
    storageBucket: 'desire-b0903.firebasestorage.app',
    measurementId: 'G-MP5BH51D3Z',
  );
}
